version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Map the USB device
    # environment:
    #   - IDF_PATH=/esp/esp-idf/
    tty: true
    stdin_open: true
    user: root  # Run as root to ensure access to USB devices

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
